SELECT ProductId, ProductName, Price, ROW_NUMBER() OVER (ORDER BY Price DESC) AS ROWNUMBER, RANK() OVER (ORDER BY Price DESC) AS RANK,  DENSE_RANK() OVER (ORDER BY Price DESC) AS DENSERANK, NTILE(12) OVER (ORDER BY Price DESC) AS NTILE
FROM Products
